src/tools/OFile.cpp
src/tools/OFile.h

Allows for per-file adjustment of output files such that from the same action you can backup some files and append others. 
Didn't add a new regtest as this feature of OFile is not used in any current action. 
Make sure these boxes are checked before submitting your pull request:

Added an option in OFile to enforce backup of files even if restarting

---

src/tools/Grid.h

Just added one inline function to the Grid class to check if a given grid has derivatives. This is something that I use in the VES module. 
btw, there is a typo in ./github/PULL_REQUEST_TEMPLATE.md: succesfully => successfully
Make sure these boxes are checked before submitting your pull request:

Add a function to check if a grid has derivatives

---

src/bias/MaxEnt.cpp
src/eds/EDS.cpp

As discussed with @hockyg, it makes sense to cross link these two implementations of similar methods.
@hockyg or @whitead: can you confirm you are ok with this change of the EDS documentation?
I also cc @a-cesari who originally wrote the MAXENT keyword.
Thanks!

Added cross refs in EDS and MAXENT

---

src/eds/EDS.cpp
user-doc/EDSMOD.md
user-doc/bibliography.bib

Refactor EDS documentation to fit into Camilloni (@carlocamilloni) submodule format, and added reference to new paper describing some features of the module.
Updated EDS module documentation so that it now appears under Additional Modules in docs. Also edited bibliography file to include a new paper referred to in the revised docs.

refactor EDS documentation 

---

src/tools/Grid.h

Added a function to the Grid for resetting the output format to the default %14.9f format. This is something that I want to use in the VES module. 

Grid: function to reset to default %14.9f output format

---

src/tools/RMSD.cpp

It looks like there is an important bug in RMSD (and RMSD based: PCA, FIT_TO_TEMPLATE, etc) when using intel compiler and -O3. I think there were many incorrect `pragma omp simd` statements. I tried to fix them.
@jpazurikova could you have a look before I merge? Thanks!
Giovanni

V2.4 fix simd

---

CHANGES/v2.4.md
src/ves/GridLinearInterpolation.cpp

Fix for a bug in TD_GRID for 2D grids when the grid spacing is not the same for both dimensions.

Fix for bug in TD_GRID

---

src/tools/Tools.cpp

I would like to make a tiny fix to the way curly braces are interpreted. Currently what happens is the following:
1. Every time we try to split a string in tokens, we ignore separators that are enclosed between braces. This allows using spaces in atom lists.
2. Each outer brace is then replaced with a single space.
What I propose is to change the second step with "Each outer brace is then removed".
The original idea was to have something similar to bash quotes (to escape separators within the quotes) but easier to parse (open and close braces have different symbols). However, I think I did a small mistake. Bash quotes are removed indeed before calling a command, and not replaced with spaces.
Consider the following:
````
METAD FILE={/path/with space/HILLS}
````
With the current parser …

Fixed behavior of braces

---

src/maze/Core.cpp
src/maze/Core.h
src/maze/Loss.cpp
src/maze/Loss.h
src/maze/Member.cpp
src/maze/Member.h
src/maze/Memetic.cpp
src/maze/Memetic.h
src/maze/Optimizer.cpp
src/maze/Optimizer.h
src/maze/Optimizer_Bias.cpp
src/maze/Random_Acceleration_MD.cpp
src/maze/Random_MT.cpp
src/maze/Random_MT.h
src/maze/Random_Walk.cpp
src/maze/Simulated_Annealing.cpp
src/maze/Steered_MD.cpp
src/maze/Tools.cpp
src/maze/Tools.h

I fixed issues with the headers from the maze module (#459). Now `cd src && ./header.sh maze` does not introduce any change to the maze module.
I would like my code to appear in release __v2.6__

header fix for issue #459

---

src/ves/VesDeltaF.cpp

Fixes a LGTM warning in VesDeltaF.cpp. Only a change in a comment. 
See https://lgtm.com/projects/g/plumed/plumed2/latest/files/src/ves/VesDeltaF.cpp?sort=name&dir=ASC&mode=heatmap#V553

Fix LGTM warning in VesDeltaF.cpp

---

user-doc/VES.md

Fix links to tutorial in VES manual due to changes in 5770d9120c4baa908a8d362b1695ba13b9879cce. 
According to what I see in the commit this should be done only in the master (not v2.5)

Update VES.md to fix links to tutorial

---

regtest/basic/rt5/plumed.dat
src/core/ActionRegister.cpp
src/tools/Tools.cpp
src/tools/Tools.h

Make the parsing of the input case insensitive by
- forcing directives to be converted in uppercase
- using interpretLabel to convert in uppercase directives
- implement a case insensitive comparison for parsing tools
in this way I can overcome some problem with const Action in ActionRegister and avoid code duplication I think
v2.6

Caseinsens

---

CHANGES/v2.5.md
src/ves/VesLinearExpansion.cpp

This fixes an issue with updating of bias potential in VES_LINEAR_EXPANSION that is present for certain integrators that call the calculation of the bias multiple times and replica exchange. 
See discussion on PLUMED group: 
https://groups.google.com/d/msg/plumed-users/kPZu_tNZtgk/LrkS0EqrCQAJ
I would like my code to appear in release v2.5

Fix for updating of bias potential in VES_LINEAR_EXPANSION

---

src/eds/EDS.cpp

Thank you to @gtribello for spotting an initialization bug. I never noticed it on my machines because it appears that the double was always initialized to 0, but now this has been made explicit :) @hockyg 

Fixed an initialization of class member in EDS

---

src/core/Atoms.cpp

A possible fix for the small annoyance of non rounded time step if MD engine uses single precision (see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/plumed-users/qv-rqQvdODE/aSfcMM_dCAAJ ).
I implemented this for myself long time back, now I saw the discussion on plumed-users, so I decided to make this PR. Feel free to ignore it if you think is not useful.
This is the rationale: the MD time step is set by the user in some input file in decimal notation, and it is extremely unlikely that the user needs more than 6 significant digits. The MD code then stores it in single or double precision. Plumed might want to stay close to the original decimal time step, instead of simply casting it to double, especially since it is only used when outputting the time, and does …

small fix for single precision timestep

---

src/colvar/Energy.cpp

The documentation of the ENERGY CV states that it calculates the total energy. For most people total energy means potential+kinetic energy. I think this should be clarified and that there is an implicit convention, followed at least by LAMMPS and Gromacs, that the energy CV is the **total potential energy** (without tail corrections as discussed in issue #567). I also believe that most if not all papers that use some energy as CV use the potential energy. Furthermore, the two citations in the ENERGY CV are papers that use the potential energy.
For the reasons stated above this PR proposes to change **total energy**  to **total potential energy** in the documentation of the ENERGY CV.
Please disregard this PR if the plan is to use the total energy in the future.
This issue was pointed out …

Update doc of ENERGY CV

---

src/drr/drrtool.cpp
src/multicolvar/InPlaneDistances.cpp
src/ves/MD_LinearExpansionPES.cpp
src/wrapper/Plumed.h

I fixed some warnings that I obtained using cppcheck 2.1. I open a pull request so as to perform the full test set.
@gtribello one of the commits (4c25861faef0f2c8febfaa2037db34dda0547126) is a bit critical, since it might be a real bug. Can you double check? In case this is a bug, we can easily backport this change.
I would like my code to appear in release __v2.6__

V2.6 some cppcheck fixes

---

src/tools/Communicator.cpp

Small change to add `long double` as supported type for the MPI communicator.
In my latest PLUMED project I use `long double` to stay on the safe side. I might eventually switch back to `double`, but since this is such a small modification for the communicator wrapper, I though it would be fine to simply add it to the code.
I would like my code to appear in release 2.7

added long double to MPI communicator

---

patches/gromacs-2020.4.diff/src/gromacs/mdlib/expanded.cpp

Related to #603, this fixes a unit mismatch between PLUMED and GROMACS. Would need to be fixed in #603 as well if that was merged, but I assume the patches to GROMACS 2020.4 deprecate #603 (which patches 2020.2).

Correct lambda meta-dynamics units

---

regtest/sasa/Makefile
src/sasa/sasa_HASEL.cpp
src/sasa/sasa_LCPO.cpp
user-doc/spelling_words.dict

The SASA module kept appearing under root, rather than under the module section in the documentation. I tried again to address this issue.
I would like my code to appear in release  2.8
- [  x ] new module contribution or edit of a module authored by you
- [ x ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 
- [ x ] I added a new regtest or modified an existing regtest to validate my changes.
- [x  ] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

try to make sasa appear under module

---

src/opes/ECVcustom.cpp
src/opes/ECVlinear.cpp
src/opes/ECVmultiThermal.cpp
src/opes/ECVmultiThermalBaric.cpp
src/opes/ECVumbrellasFile.cpp
src/opes/ECVumbrellasLine.cpp
user-doc/OPES.md

This fixes an issue with the additional modules where at the moment there is a listing for `EXPANSION` that is incorrect (between VES and MAZE in the list on https://www.plumed.org/doc-master/user-doc/html/_add_mod.html). 
It seems that this is due to the usage of `EXPANSION_CV` in the OPES manual. I have changed this to `OPES_EXPANSION_CV` in the relevant places and this seems to fix the issue (as tested on my laptop). 
@invemichele should check that he agrees with these changes. 
I would like my code to appear in release v2.8 (master)

Fix incorrect EXPANSION module in manual

---

src/gridtools/FindContour.cpp

@gtribello can you double check this? Cppcheck 2.4.1 tells me this:
```
[gridtools/FindContour.cpp:103] (warning) :duplInheritedMember: The class 'FindContour' defines member variable with name 'mydata' also defined in its parent class 'ActionWithVessel'.
```
I suppressed the error in order to use cppcheck 2.4.1 on master branch, but I suspect that cppcheck is correct. If this variable was added by mistake I would merge this branch.
I would like my code to appear in release __v2.8__, but if it's a bug fix it should be backported

Removed an inconsistency detected by cppcheck

---

patches/gromacs-2021.config

Knowing which PLUMED version has patched GROMACS is potentially valuable information for GROMACS and PLUMED users and developers troubleshooting their runs.
Closes #737
I would like my code to appear in release 2.7 and master

Let GROMACS runtime logs show PLUMED patch active

---

regtest/scripts/fixzeroes.sh

Change to fixzeros.sh script in regtests to make it more general. For example, now values of the form `-0.00` are correctly handled. This change is needed to make the PR #759 pass the CI tests.
This passes all CI tests, see https://github.com/ves-code/plumed2-ves/actions/runs/1482785956 
I would like my code to appear in release v2.8

Change to fixzeros.sh script in regtests

---

src/opes/OPESmetad.cpp

The doc page for OPES_METAD is displaying only up to this line `Ftg: BIASVALUE ARG=Ftg_func`, see https://www.plumed.org/doc-master/user-doc/html/_o_p_e_s__m_e_t_a_d.html
When clicking on `Ftg:` one can see that the rest of the page is wrongly included among the components of `BIASVALUE`.
I fixed the problem simply by renaming `Ftg_func` to something without an underscore, but this might happen also somewhere else in the doc, and probably the function "click to see the output components" should be made more robust.
I would like my code to appear in release __2.8__

Fix OPES_METAD html doc

---

src/s2cm/COPYRIGHT
src/s2cm/S2ContactModel.cpp
user-doc/S2CMMOD.md

Fixes some issues with incorrect manual generation for the S2CM module. 
I would like my code to appear in release v2.8

Fix for S2CM manual generation

---

patches/gromacs-2020.6.diff/src/gromacs/mdlib/expanded.cpp
patches/gromacs-2020.6.diff/src/gromacs/mdlib/expanded.h
patches/gromacs-2020.6.diff/src/gromacs/mdrun/md.cpp
patches/gromacs-2021.4.diff/src/gromacs/mdlib/expanded.cpp
patches/gromacs-2021.4.diff/src/gromacs/mdlib/expanded.h
patches/gromacs-2021.4.diff/src/gromacs/mdrun/md.cpp

Update GROMACS expanded ensemble patches to include the new bias
query not updating the forces, and clarify the user interface.
Based on discussions with @GiovanniBussi, @mrshirts, @wehs7661.
I would like my code to appear in release v2.8, ideally.

Update GROMACS expanded ensemble patches

---

src/crystallization/EnvironmentSimilarity.cpp

Existence of PDB files for reference environments was not checked before reading them. Thus, absence of reference environments would not raise an error but rather give a wrong result. This PR checks for PDB files before reading them and raises an error if they are not found.
In the master branch this bug is fixed by #832 .
I would like my code to appear in release v2.8

Fix bug in Environment Similarity - check for pdb files before read 

---

regtest/basic/rt-make-extracv/main.cpp
regtest/basic/rt-make-extracv/output.reference
src/colvar/ExtraCV.cpp
src/core/Atoms.cpp
src/core/Atoms.h
src/core/MDAtoms.cpp
src/core/MDAtoms.h
src/core/PlumedMain.cpp

This is to complete the implementation of extra CVs (computed in the MD code), see #83 .
What I add here is an extra plumed cmd to allow the MD code to know if an extra CV is needed at the step or not.
This can be used to enable:
- multiple time stepping
- monitoring with large STRIDE
possibly useful for expensive CVs.
I would like my code to appear in release __2.9__

Added cmd("isExtraCVNeeded")

---

src/tools/SwitchingFunction.cpp
src/tools/SwitchingFunction.h
src/ves/TD_Multicanonical.cpp
src/ves/TD_Uniform.cpp
user-doc/tutorials/others/ves-lugano2017-02-ves1.txt
user-doc/tutorials/others/ves-lugano2017-03-ves2.txt

This a exactly like PR #927, but rebased on the v2.8 branch
As stated there, this PE should also resolve #643 : now TexLive2021 compiles the manual
The formula for the COSINUS switching function was not visualized correctly in the documentation, I also correct a small typo in the developer documentation
I would like my code to appear in release v2.8

Small Correction in switching function documentation to 2.8

---

src/opes/ECVmultiThermalBaric.cpp
src/opes/OPESexpanded.cpp
src/opes/OPESmetad.cpp

same as #938 but targeting v2.9

V2.9 - add to OPES same MPI-related error messages of METAD

---

regtest/multicolvar/rt-link/config
regtest/multicolvar/rt-link/main.cpp

@gtribello it looks like this test is not using MPI. Is this change ok?
To use MPI in a `make`-type regtest, you need to explicitly call `MPI_Init` and `MPI_Finalize` (see e.g. [here](https://github.com/plumed/plumed2/blob/b20517e8f0d1d7ecf1650d0b39c11e6f8a43a363/regtest/basic/rt-make-2/main.cpp#L143-L153)).
Actually, these two tests are those causing [this problem on Rockylinux](https://github.com/plumed/plumed2/pull/933#issuecomment-1556302511). With this change I guess only the `rt-make-2` test will fail. I am still investigating on the reason.

It looks like this test does not really use MPI

---

src/gridtools/FindContourSurface.cpp

I found two `#ifndef DNDEBUG` in gridtools: I think this is a typo for `#ifndef NDEBUG`, since if I do a grep searching for `DNDEBUG` I only find results with the command line definition for `NDEBUG` (`-DNDEBUG` and not `-DDNDEBUG`).
This is a really small bugfix I think it should be compatible with v2.8 and subsequents

fixed a typo?

---

regtest/.gitignore
regtest/unittest/Makefile
regtest/unittest/rt-getGoodNumThreads/Makefile
regtest/unittest/rt-getGoodNumThreads/config
regtest/unittest/rt-getGoodNumThreads/output.reference
regtest/unittest/rt-getGoodNumThreads/testNumThreads.cpp
src/tools/OpenMP.cpp
src/tools/OpenMP.h

I checked out that the class `PLMD::OpenMP` was been used as a namespace: it only has static methods and no members
I think these small modifications may improve code readability: 
- `PLMD::OpenMP` is now a namespace
- the warning workaround in `PLMD::getGoodNumThreads` is now a commented input instead of a C-style cast, so there is no unused variable to throw a warning
- in Tools/OpenMP.cpp `OpenMPVars` is now explicitly a singleton with a line of documentation and a private constructor
A question: reading `PLMD::getGoodNumThreads(T*,unsigned)`, it looks like it returns either `getNumThreads()` or `1`, is this the wanted behaviour? If yes I'm updating the documentation, there should be a unit test to check that the wanted  behaviour is present.
I would like my code to appear in release …

small changes in the openMP settings

---

.github/workflows/ci.yml
docker/centos7

Python 3.7 has finally come to its EOL,I'm starting a series of PR for trying to see if python 3.9 can be used without to many modifications

Updated python version requested from the ci

---

src/core/PlumedMain.cpp
src/core/PlumedMain.h
src/setup/Load.cpp
src/tools/DLLoader.cpp
src/tools/DLLoader.h

Knowing the problems with the new direction of pycv in Unix I added the possibility to LOAD shared object with the RTLD_GLOBAL option, if needed the standard behaviour is not changed.
I changed some names in the load method of PlumedMain, for readability.

Adding GLOBAL keyword to LOAD action

---

.github/workflows/macWF.yml

In #967, related to the EOL of python3.7, I lost the "py37" in the macports-CI, here I removed it

Removed py37 and py38 from macports CI

---

scripts/mklib.sh

I added a trap into mklib.sh so that if anything happens during the execution the temporary files will be automatically removed.

mklib deletes tmp files also in case of failure

---

src/opes/ECVlinear.cpp
src/opes/ECVmultiThermalBaric.cpp

See https://github.com/plumed/plumed2/pull/990
Unfortunately I cannot test the intel compiler on my machine. My guess is that previous attempt did not work because this line was optimized away 
```
if(!std::isnan(std::numeric_limits<double>::quiet_NaN()))
```
Anyway, I now completely removed any NaN and instead use a very unlikely default value, that in practice will do the same job.

OPES: second attempt at fixing NaN problem for intel compiler

---

src/tools/Exception.h

I encoundered a case i which the `if (!(test)) plumed_error() << PLMD::Exception::Assertion(#test)`, the plumed_dbg_massert macro expansion with NDEBUG, is not optimized away, and this patch is the least invasive thing to do:
`if constexpr(false)` is guaranteed to be evaluated at compile time, so that the rest of the line is ignored.
I think helps in improving the code optimization after inlining a function, at least that is what I think it happened in my case
I would like my code to appear in release 2.10/2.9 (this is a single commit, it can be easily rebased on the 2.9)

Removing the should from Exception.h

---

plugins/pycv/PlumedPythonEmbeddedModule.cpp
src/tools/Pbc.cpp
src/tools/Pbc.h
src/tools/Tools.h

As suggested in the review of #1001 I implemented a "memory view" for Pbc::apply.
Now Pbc::apply can be used with any data stored in a "xyzxyzxyz..." fashion (aligned like a `std::vector<PLMD::Vector>`): Plumed will process it like a `std::vector<PLMD::Vector>`.
It is "zero cost abstraction" in the sense that you may pay little more compilation time but there should be no cost at runtime.
And as now the memory view is in a very crude status, with only the parts useful to make Pbc::apply work.
It may need to be relocated in ad ad hoc header.
You should note that I inlined the "generic" branch of Pbc::distance into Pbc::apply. Because calling the original Pbc::distance from Pbc::apply with the new changes results in a heavy slow down.
Now Pbc::apply is 20-30% faster when using non …

Memory view (for pycv)  and adding constexpr in Tools::pbc

---

src/core/ActionAtomistic.cpp
src/core/ActionAtomistic.h
src/generic/FitToTemplate.cpp

@gtribello I tried to optimize wholemolecules, it's mostly inlining stuff but you might want to check if I did things right.
What worries me a bit is that even with this impressive improvement (almost a factor 2) I am back to timings pre-htt. Here's my timing (no graphs, but it should be easy to understand):
```
pre htt: 00b63d594487f4445e7d6748ef65c246c7ce3173
PLUMED:                                               Cycles        Total      Average      Minimum      Maximum
PLUMED:                                                    1     2.426496     2.426496     2.426496     2.426496
PLUMED: 1 Prepare dependencies                          2000     0.001444     0.000001     0.000000     0.000012
PLUMED: 2 Sharing data                                  2000     0.493404     0.000247 …
```

Optimize wholemolecules

---

src/core/DomainDecomposition.cpp

This addresses issues #1025 @GiovanniBussi
This commit removes the call to set that is discussed in issue #1025.  I don't see that this making a noticeable difference to performance when compared with master but I am possibly not running on the correct setup.
- [x ] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [x ] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.
- [ x] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).

Removed call to set that is used in DomainDecomposition.

---

src/cltools/Benchmark.cpp

This is to add the possibility to simultaneously test multiple kernels with
the benchmark application.
In short, one can do
```
plumed-runtime benchmark --kernel /path/to/libplumedKernel.so
```
to test a specific kernel. Alternatively
```
plumed-runtime benchmark --kernels /path/to/one/libplumedKernel.so:/path/to/other/libplumedKernel.so
```
to test two (or more) kernels. Test is alternating from one kernel to the other in random order at every
step so as to make the timing homogeneous. The idea is that possible system overloading will affect
equally both kernels, and the comparison will be more fair.
I attach a notebook where I show that in this manner timings are reproducible. To do so
I use
```
plumed-runtime benchmark --kernels this:this
```
to compare the kernel of the current PLUMED …

Added possibility to compare multiple kernels

---

scripts/mklib.sh

This should address the missing "core/Atoms.h" in the nest, more precisely  it will only state that the header is deprecated, and then make proceed the compilation until there is a failure on an `Atoms` method that does not exists anymore, this may guide to update easier some error in the nest.
I also patched the template cv, so that now it can compiled as it is generated by `plumed newcv`

Mklib deprecation warning for "core/Atoms.h"

---

src/cltools/Benchmark.cpp

Added:
- stop after a maximum time
- benchmark domain decomposition runs
- comparative analysis on different versions
- sleep to simulate MD code calculation
See [documentation](https://github.com/plumed/plumed2/blob/27e789cfe1e3bfd895efd89c695c6468d4bb75b8/src/cltools/Benchmark.cpp#L45-L156)
@carlocamilloni could you share the SAXS test case you were running on MPI? I want to test it with this benchmark tool, to see if by running multiple versions at a time we get more precise results.
I would need:
- plumed input file
- all accessory files (pdb etc) if needed
no trajectory should be needed

Extensive improvements in benchmark tool

---

src/core/ActionWithValue.cpp
src/core/Makefile

I am working with this input file:
```
WHOLEMOLECULES ENTITY0=1-100000
c: CENTER ATOMS=1-100000
pos: POSITION ATOM=c
RESTRAINT ARG=pos.x AT=0.0 KAPPA=1
```
By just replacing a loop with a blas call I can see a significant gain. I only tried in my laptop, but I guess this could be quite general (when optimized blas are available).
Below the full results, comparing: v2.9, master before this commit, and master with this commit.
The slowdown wrt v2.9 is reduced from 26% to 18%
```
BENCH:  Kernel:      /Users/bussi/plumed2/tmp/v2.9-mpi-ref/lib/libplumedKernel.dylib
BENCH:  Input:       plumed.dat
BENCH:  Comparative: 1.000 +- 0.000
BENCH:                                                Cycles        Total      Average      Minimum      Maximum
BENCH:  A Initialization …
```

Replaced some bottleneck loop with blas

---

src/core/ActionAtomistic.cpp
src/core/ActionAtomistic.h
src/core/ActionWithValue.cpp
src/core/ActionWithVirtualAtom.cpp
src/core/Makefile

I am again working with this input file:
```
WHOLEMOLECULES ENTITY0=1-100000
c: CENTER ATOMS=1-100000
pos: POSITION ATOM=c
RESTRAINT ARG=pos.x AT=0.0 KAPPA=1
```
In this PR I tried to optimize loops like this:
```
for(const auto & a : atom_value_ind) {
plumed_dbg_massert( ind<forcesToApply.size(), "problem setting forces in " + getLabel() );
std::size_t nn = a.first, kk = a.second;
xpos[nn]->inputForce[kk] += forcesToApply[ind]; ind++;
ypos[nn]->inputForce[kk] += forcesToApply[ind]; ind++;
zpos[nn]->inputForce[kk] += forcesToApply[ind]; ind++;
}
```
Into loops like this:
```
for(const auto & a : atom_value_ind_grouped) {
const auto nn=a.first;
plumed_dbg_assert(ind<forcesToApply.size()) << "problem setting forces in " << getLabel();
auto & xp=xpos[nn]->inputForce;
auto & …
```

Optimize grouping indexes

---

src/core/ActionAtomistic.cpp
src/core/ActionAtomistic.h
src/core/DomainDecomposition.cpp
src/core/DomainDecomposition.h
src/generic/DumpAtoms.cpp
src/generic/DumpMassCharge.cpp
src/generic/FitToTemplate.cpp
src/generic/Plumed.cpp
src/generic/PrintNDX.cpp
src/generic/WholeMolecules.cpp
src/generic/WrapAround.cpp

This is my try at the rework of the stuff for speeding up the applying of forces in domain decomposition.  I have tried to do  this in the way we discussed in the meeting on Wednesday.  You can see it speeds up the ally force part.  However, the sharing of data is slowed down.  I think this may because I have not made the changes to DomainDecomposition correctly.
Can you take a look @GiovanniBussi and let me know if I am doing anything wrong.
````
BENCH:  Kernel:      this
BENCH:  Input:       plumed.dat
BENCH:  Comparative: 1.000 +- 0.000
BENCH:                                                Cycles        Total      Average      Minimum      Maximum
BENCH:  A Initialization                                   1     0.006875     0.006875     0.006875     0.006875
BENCH:  B0 First step …
```

Split list of forced actions from list of non-forced actions in domain decomposition

---

src/cltools/Driver.cpp
src/core/Action.cpp
src/core/Action.h
src/core/PlumedMain.cpp
src/core/PlumedMain.h
src/setup/Restart.cpp

As discussed in the meeting today, if we make this change many eggs in the nest will pass as the problem with them is that people have upload a PLUMED input file that has RESTART in it but no hills file.  If we thus suppress RESTART when we run parse-only mode the tests should pass.
I would like my code to appear in release 2.9

deactivate restart during parse only runs

---

src/tools/Tree.cpp

Avoid doing searches by atom number in the PDB for every distance calculation. 
Only relevant for startup, not for the following calculation, but given the scaling of the EMST calculation with the number of atoms I think it's relevant. I didn't make precise timings, but my understanding is that:
- before this, time scales as `N_wholemolecules * N_wholemolecules * log(N_PDB)`
- after this, time scales as `N_wholemolecules * N_wholemolecules`
The additional `*log(N_PDB)` comes from the need to search the index of each atoms in the PDB in the inner loop. 
I tested on this input:
```
MOLINFO STRUCTURE=1s72.pdb WHOLE # big PDB with ~ 90k atoms
WHOLEMOLECULES ENTITY0=1-100000 EMST
```
Startup time decreases from ~ 12 minutes to ~ 25 seconds. 
@maxbonomi let me know if you have any concerns with …

Optimized EMST setup

---

src/cltools/Benchmark.cpp

I did some modification to the Benchmark.
After removing a few warnings and adding some `const`, I added a few options for the "simulated atoms" and changed how existing one, "the line", works.
The options that I added are:
- *an uniform distributed cube*
- *an uniform distributed sphere*
- *two uniform distributed sphere that should not touch each other*
- *a static "simple cubic"* distribution
the distributed ones are randomly generated at each step, so I think that are not suited to test a neigbour list
the simple cubic do not change with advancing steps, but I may add to it a way to make the atoms "oscillate" around their positions
The original line was adjusted from 
```c++
for(unsigned j=0; j<natoms; ++j)
pos[j] = Vector(step*j, step*j+1, step*j+2);
```
to
```c++
for(unsigned j=0; …
```

Benchmark distributions

---

regtest/basic/rt-make-moduleMap/Makefile
regtest/basic/rt-make-moduleMap/config
regtest/basic/rt-make-moduleMap/main.cpp
src/core/Makefile
src/core/ModuleMap.cpp
src/core/ModuleMap.h
src/maketools/makeModuleMap

@gtribello, @GiovanniBussi I have set up a simple module map
It can be used as `PLMD::getModuleMap().at("actionName")`[^1] to return the name of the module that includes that action (even if the module is not active in the current installation)
for 2.10 it is possible to add also an extra function that returns a `std::optional` with the module name to not doing the `.count("actionname")` before calling the at (that may throw), since `std::optional` is c++17
Since regex are scary I put a link to a site tha visualize the one used in the new maketool script
The new maketool script uses pure bash, I think there should not be problem between bash versions for the regex that I used, and I used pure bash to avoid having the user to install gawk or perl
I do not know if you like the requirements …

Added a simple module map

---

scripts/mklib.sh
src/core/PlumedMain.cpp

The `plumed mklib` script in v2.10 works as a makefile, so that if a .so is already present it is not recompiled. This is necessary for thread safety. This however causes a problem in the plumed nest where the .so file produced by v2.9 is not regenerated when using master. One possible solution is to encode the version name in the .so file.
With this PR, when using
```
LOAD FILE=file.cpp
```
A `.so` file will be generated with name `file.2.10-dev.so`.
Notice that the change is apparent only when using `LOAD`, and not when using `plumed mklib` directly. In other words:
```
plumed mklib file.cpp
```
will still generate a file named `file.so`.
I did it in this way, which is completely transparent to users. Indeed, the `.so` file created by `LOAD` is a temporary that is never explicitly …

Load library version

---

src/cltools/Driver.cpp
src/core/Action.cpp
src/core/ActionRegister.cpp
src/core/ActionRegister.h
src/core/ActionWithValue.cpp
src/core/PlumedMain.cpp
src/core/PlumedMain.h
src/multicolvar/XAngle.cpp

I have been doing some work on improving the PlumedToHTML code that generates the annotated input files for the tutorials and nest.  The work is described in [this PR](https://github.com/plumed-nest/plumed-nest/pull/118).  As part of this I have had to make some modifications to PLUMED.  In particular, when you call PLUMED driver in parse only mode you can ask it to output two json dictionaries that contain:
1. How any shortcut keywords are expanded into the longer input
2. The definitions of the quantities that have labels in the input file
Getting the definitions of the labels directly from plumed when you run driver is superior to getting this information from the syntax file as:
1. You are able to distinguish whether objects are scalars, vectors, matrices etc this way.
2. You can find …

Fixes to documentation generators for PlumedToHTML

---

patches/qespresso-5.0.2.diff/PW/src/plugin_forces.f90
patches/qespresso-7.0.diff/PW/src/plugin_initialization.f90
patches/qespresso-7.2.diff/PW/src/plugin_initialization.f90

I checked out the files from the v2.8 (see #1083)
This time should be mergeable to the master branch
I would like my code to appear in release v2.9++

Merged for the  qe patches from 2.8 into 2.9

---

src/cltools/Benchmark.cpp

I have been digging into many benchmarks lately, and this small addition eases the work for me and will be useful for any benchmark user in the future.
Now the first output of the benchmark will be something like this:
```
BENCH:  Welcome to PLUMED benchmark
BENCH:  Using --kernel=this
BENCH:  Using --plumed=plumed.dat
BENCH:  Using --nsteps=2000
BENCH:  Using --natoms=100000
BENCH:  Using --maxtime=-1
BENCH:  Using --sleep=0
BENCH:  Using --atom-distribution=line
BENCH:  Initializing the setup of the kernel(s)
```
That is for a run here is `plumed benchmark` with no options given, if an option like `--shuffled` is given a line with `BENCH:  Using --shuffled` will appear.
I find this useful for reproducing the bench later, or to share a clearer file. 
It may also be useful in the case of …

Adding a small header to the benchmark utility

---

src/colvar/CoordinationBase.cpp

I changed how the couples are traversed in the CoordinationBase `calculate()` method, by passing from a "striped" traversal to a "block" one.
I get a 3%-5% speedup on my local machine.
---
Here are some results I got on my workstation, the graph show the time spent in `calculate()` relative to the time spent in calculate in the master branch
for 4 mpi processes and 2 threads each one
for 1 process with 8 threads (Here I did not expect performance improvement)
---
Before removing the draft status I'd like to see if it is possible to not store the couples in the neighbor list if the user asks for a fixed list
I would like my code to appear in release 2.10 (but I think this can rebased on 2.9)

Small optimization in CoordinationBase

---

src/cltools/Benchmark.cpp

I added the handler for SIGTERM to the benchmark CL.
I tried with `kill -TERM pid` and it seems to work
I made the info message more pedantic.
@GiovanniBussi I added the handler correctly or should I add another function?

Added sigterm to the signal handler for Benchmark

---

src/wrapper/Plumed.h

I removed the old-style casts in Plumed.h.
Now when Plumed.h is in "c++ mode" will use static_cast or reintrpet_cast 
I used `-Werror=old-style-cast` to find the casts and i changed to static when gcc suggested to change to static and reintepret otherwise or when no suggestion were made.
I am not 100% sure to have changed every casts, but at least the ones that affects the gromacs compilation are done plus some more found with searching `\(.*?\)\w`.

Removed old-style-cast from Plumed.h

---

src/cltools/Benchmark.cpp

I changed the help text in the benchmark to reflect better its usage

minimal change in the benchmark help text

---

src/cltools/Benchmark.cpp

I am writing a small piece for the school explaining how the benchmark can be used, and I needed to visualize the trajectories, these modifications were the simplest thing to obtain the trajectories.
`plumed benchmark --dump-trajectory trj.xyz +other options` dumps the trajectory that would be used in the benchmark to the "trj.xyz" file.
By default write an XYZ compatible with `plumed driver`, but with an environment variable set (`PLUMED_BENCH_EXTENDED_XYZ`) it can output an extended xyz file;
I would like my code to appear in release v2.10

set up a very simple way for visualizing the benchmark trajectories

---

src/wrapper/Plumed.h

In theory, calling getenv a second time could return NULL after previously returning non-NULL, which would be undefined behavior when passed to strcmp. Re-using the non-NULL value is slightly safer, and keeps clang's static analyzer happier.

Reuse result from getenv

---

src/tools/Tools.h

Remove extraneous field assignment. This breaks the build for me when trying to compile the master branch using https://github.com/plumed/conda/.
Since this was not caught in the 6 months since this code was introduced, maybe it is not used anywhere in the code base? I'm not sure why this is failing now.

Handler class does not have a `watch` field

---

src/bias/LWalls.cpp
src/bias/UWalls.cpp

This is about #1091, now if a lower wall is asked with an odd exponent, it should give the correct force, and I think also the energy because ` ene += k * power;` now will contribute with a positive and repulsive term in any case.
I think we need some more tests to check this.
I would like my code to appear in release v2.9

FIX-2.9 Now the forces from LWALLS should be correct 

---

src/core/ActionRegister.cpp
src/core/CLToolRegister.cpp
src/core/RegisterBase.h

I was running some tests on some previous commit (where regtest/clusters/rt-dfg1/config had a wrong module prerequisites instead of `plumed_modules="adjmat clusters"`) and the exception text `+++ assertion failed: m.count(key)>0` felt not helpful.
I think that the text `+++ assertion failed: m.count(key)>0, Missing key is "KEYNAME"` feel a little more helpful.
I think these few lines may help at least in doing a `git grep KEYNAME` in src or a `plumed manual KEYNAME` to find at least which module has not been loaded.
---
An maybe we can use #1063 for giving directly that info, I do not know if directly in the register or also in an ad-hoc cltool or in cltools/Manual.cpp
---

More helpful exception text for Registerbase

---

regtest/basic/rt-make-exceptions/main.cpp
src/wrapper/Plumed.h

While trying to add a plumed module to gromacs I got a few `-Wstringop-truncation` warnings
with this PR I am trying to address them in a way that does not imply too many changes in the original plumed codebase.
I am starting this as a draft because likely this branch will get some more commit
--- 
the changes in the tests are to make the compiler complain about the tested code and not the code of the test.

Plumed h for gromacs

---

.github/workflows/linuxWF.yml
src/tools/MergeVectorTools.h

In this PR I will set up some modifications to the code in order to make possible to compile all plumed with nvhpc v24.3.
As now is a work in progress, I do not know if the CI will even start and some regtests are failing on my pc, the PR is set up to check easily if the modifications do not break other compilers against the master branch.

Compiling with NVHPC

---

src/bias/Walls.cpp

This should solve #1091, see the issue for the problem
I want to benchmark the  (-x) version against the (abs(x)) version, but maybe that is a thing for another PR.
Shall we add a new test to check the sign in this and maybe other COLVARs?

FIX - Changing the sign of the argument of the exponential in  LOWER_WALLS

---

configure
configure.ac

The configure code was unconditionally adding `-Wl;--no-as-needed` to the flags, even though these are not valid on macOS.
I'm not sure why this needs `--no-as-needed` on linux on the first place, @luigibonati do you remember why this is the case?

Fix building shared libraries on macOS with `--enable-libtorch`

---

src/drr/DRR.cpp
src/drr/DRR.h
src/drr/DynamicReferenceRestraining.cpp

The previous implementation updates the internal states partially in calculate(), which should be done in update(). This commit fixes the issue.
This PR refactors the DRR implementation by moving the update of the eABF grid and the estimators in the `update()` function from `calculate()`.

DRR: correctly separate the calculate and update

---

src/cltools/Benchmark.cpp

Reading the code again, I discovered that shuffled and domain decomposition could be automatically changed without the user input, during the setup of the benchmark,
I changed the output of the header to reflect that.
Sorry for the Friday PR, this is a small thing that I am sure to forget

Now the header is correct also in mpi run benchmark run

---

python/cplumed.pxd
python/plumed.pyx

Fixes #1128. I can confirm this fixes the issue for `metatensor` actions.
However, I'm not sure how to test that `pycv` still works fine, is it included in the CI test suite?

Do not hold Python's GIL when running commands

---

regtest/scripts/run

As the title, with this typo, regtest/scripts/check marks as "successful" the few tests that use `plumed_custom_skip` when they are skipped, found while working on #1134
I would like my code to appear in release 2.9->2.11

Removed a typo from regtest/scripts/run

---

src/tools/Pbc.h

Since my previous version of the code was producing a lot of warning I set up the control value for a "dynamic array" in a more modern (and less bugprone) c++ way.
I would like my code to appear in release __v2.10__

More modern way of setting the biggest size_t in PBC

---

regtest/basic/rt-cregex-backward-compatibility/Makefile
regtest/basic/rt-cregex-backward-compatibility/config
regtest/basic/rt-cregex-backward-compatibility/out.reference
regtest/isdb/rt-Metainference-averaging/config
regtest/isdb/rt-jcoupling-string-type/config
regtest/isdb/rt-metainference-mc-chunksize/config
regtest/isdb/rt-metainference-optisigmamean-sem-max/config
regtest/isdb/rt-metainference-optisigmamean-sem/config
regtest/isdb/rt-metainference-regres-zero/config
regtest/isdb/rt-metainferencebase-averaging/config
regtest/isdb/rt-metainferencebase-regres-zero/config
regtest/isdb/rt-metainferencebase-sem-max/config
src/config/Config.h
src/config/Config.inc.in
src/maketools/update-config-txt.sh

> [!Note]
>rt-coverage-antibetarmsd fails due to what is being solved here #1166 
As what's told in #1175 I'm pushing a couple of commit that should solve the backward compatibility with "absence" of `cregex`.
In the first two I declare that cregex is there in config.txt (`plumed config has cregex`) and in `PLMD::config::hasCregex()`
I would like my code to appear in release v2.10

Now cregex "appears" to be included (for backward compatibility)

---

src/cltools/GenExample.cpp

>afterthought:
>The aim of this was to cover some segmentation fault.
> This does not solve those segmentation faults
> But I think that that is due some problems that cam from what happen after `error` is used. I just solved the no badge problem in some part of the manual, but some pages like the one about the `...` now it should render correcly, or at leas running an example with standalone things when you do not care about the status badge
In #1183 I randomly discovered a sigsegv when running gen_example on plumed tools.
It looked like the "nobadge" status was missing from the options when creating a badge, now it displays a ![](https://img.shields.io/badge/-nobadge-36454F.svg) in that case.
`"nobadge"` looks like it is the default status when `gen_example` is called with no arguments, …

adding the "nobadge" badge to gen_example

---

src/cltools/GenExample.cpp

This is the same tiny bit I have set up in a PR for Plumed2HTML.
The problem is that the `div` elements in the listing of the plumed examples in the manual causes extra new lines when copy-pasting the plumed examples.
for example 
```
dist: DISTANCES ATOMS1=1,300 ATOMS2=1,400 ATOMS3=1,500
```
gets pasted as:
```
dist: DISTANCES ATOMS1
=1,300 ATOMS2
=1,400 ATOMS3
=1,500
```
I do not know if is the keyword element or the tooltip that pops up, but using to `span` will solve that problem (at least on Firefox).
I would like my code to appear in release v2.9

now the div are span for the kw in the listings

---

CHANGES/v2.10.md
src/multicolvar/Distances.cpp

To maintain compatibility with the old version of PLUMED the DISTANCES shortcut creates a group of vatoms that are at the center of mass for each pair of atoms that you are calculating the distance between.  This was useful for implementing methods such as SMAC.  Typically, this option has been used with this version of a DISTANCES command:
````
d1: DISTANCES ATOMS1=1,2 ATOMS2=3,4 ...
`````
To my knowledge, no one has ever used this when doing something like:
````
d1: DISTANCE GROUPA=1-10 GROUPB=11-100
````
Even though that is possible.  This PR prevents this second option and thus breaks back compatibility with older versions of PLUMED.  However, I am pretty certain no one was using the atom positions that are created by the second command anyway.  The reason for deleting the …

Removed creation of vatoms when using DISTANCES GROUPA/GROUPB syntax

---

src/core/ActionWithArguments.cpp
src/tools/Keywords.cpp

This is the PR about the problem I saw in #1167 and #1166
I think that the intended use of the original change I am fixing was to change the warning into an error, since I saw that it generates SEGFAULTs in case of keeping it as 
a warning.
But the `plumed_merror` in the `Keywords` scope lose the information of having the information of the "culprit action" (and I think that `plumed_merror` is deprecated in favour of `plumed_error`, right?). So I simply changed the `->warning` into an `->error` to have the name of the action that arises the problem
I think this is more a "dev-side" problem than a "user-input" one, but  it is still better to state to the user what is the action that may cause the error, since it can be "workarounded" as I did in #1166
`checkArgumentType` is only used in a …

[FIX] Moving the checkArgumentType error to its caller

---

src/core/Action.cpp

This is a fix for issue #1198 
The reference to the Keywords object is Action is only valid during construction.  The underlying object is destroyed after the constructor is finished, so the reference to Keywords is no longer accessible.  The keywords.exists("NO_ACTION_LOG") is thus not available if you call error during calculate. If I just remove that if statement it all works fine.

Fix for issue 1198

---

src/core/ActionShortcut.cpp
src/core/PlumedMain.cpp
src/gridtools/KDE.cpp
src/valtools/SelectWithMask.cpp

This is a fix for a bug that I discovered while working on PR #1199 
When creating actions from shortcuts you need to use readInputWords rather than readInputLine as readInputLine prints and clears the bibliography after creating the action.  In contrast readInputWords keeps the bibliography and only prints it at the end of the log one the whole plumed input is read.  This PR changes all the readInputLine commands in shortcuts to readInputWord commands so the bibliography is rendered properly again.

Fixed bug with shortcuts and citation manager

---

README.md

As @carlocamilloni noted the API for the CI badges has changed, I updated the ones for the supported version, then we have to update 2.10 and master
I would like my code to appear in release v2.9

Updated the CI badges to the new API

---

src/core/ParallelTaskManager.h
src/tools/Pbc.h
src/tools/Tools.h
src/tools/View.cpp
src/tools/View.h

@gtribello
as we discussed I am moving the code into easier-to-use places
I am doing a commit per piece of code, starting from the View.
The plan is
right?
Colvar input and ouput will likely end up in the same file
I will set up the PR directly with the versions of those classes that works for openacc, to simplify the rebasing/merging of #1206 
For the changes in Pbc, as now I am using `using` to speed up, but in a second moment we can change "memoryView" to plain view

Moving the support code in a easier to use place

---

src/core/ParallelTaskManager.h

Hi @gtribello when I did #1217 I forgot to change `D` to `input_type` in the openACC regions

Fixed type in the openacc guarded regions

---

src/wrapper/Plumed.h

GCC 12.1 can warn like
```
warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound
512 equals destination size [-Wstringop-truncation]
```
PLUMED intends to ensure that the C string is null terminated and has a known maximum length, which this change makes clear to the compiler.

Avoid warning about strncpy

---

patches/gromacs-2025.0.config
patches/gromacs-2025.0.diff/cmake/gmxManagePlumed.cmake
patches/gromacs-2025.0.diff/cmake/gmxManagePlumed.cmake.preplumed
patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedMDModule.cpp
patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedMDModule.cpp.preplumed
patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedOptions.cpp
patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedOptions.cpp.preplumed
patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedOptions.h
patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedOptions.h.preplumed
patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedforceprovider.cpp
patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedforceprovider.cpp.preplumed
patches/patch.sh

@carlocamilloni @GiovanniBussi I am setting up the patch for gmx 2025.
Due to the gromacs implementation that I set up, the patch is quite lighter.
Due to the gromacs implementation that I set up, the patch lacks a few features you are used to.
As of now, I am simply adding the multisim capabilities that are not present in the "vanilla" plumed-in-gromacs implementation.
**Since gmx2025 is not out yet I am targeting the branch `release-2025` and in particular the commit `78e37c9cca4d87cfcfc8b9919ce044d54a29e6eb`.**
I added a new patch "mode" that does not copy the extra headers and configuration bits, but that might be an overshoot
I am targeting 2.10, is that ok?

V2.10 patches/gromacs2025

---

src/colvar/MultiColvarTemplate.h
src/core/ParallelTaskManager.h
src/secondarystructure/SecondaryStructureBase.h
src/volumes/ActionVolume.h

@Iximiel and @GiovanniBussi, I am not entirely happy with the GPU implementations we have thus far.  My concern is that we have thus far implemented the GPU parallelization in three of the methods that use the ParallelTaskManager class.  All three of these implementations use applyForces part of the ParallalTaskManager differently.
* `MultiColvarTemplate` gathers the derivatives on the atoms using the `gatherForces` method I wrote and then uses a mechanism for gathering the virial that is implemented in `ParallelTaskManager`
*  `SecondaryStructureBase` has a custom method for gathering the forces on the atoms that is implemented in `SecondaryStructureBase` and then uses the mechanism for gathering the virial in `ParallelTaskManager`
*  `QuaternionBondProductMatrix` uses a custom method …

Added new mechanism for forces in ParallelTaskManager

---

src/cltools/Benchmark.cpp
src/tools/TrajectoryParser.cpp
src/tools/TrajectoryParser.h

I ported the trajectory reader to the benchmark utility, as planned. I also added a rewind  function for `FILE*`-style files (like internal xyz, gro) to loop over the file in the benchmark.
This can be used to benchmark on more real-world-alike trajectories for some complexe CVs
For the non rewindable trajectory readers the workaround is to run `plumed benchmark --dump-trajectory file.xyz` and then run the bench with the new file with `-ixyz`.
The next step is to  maybe add a way of replicate the trajectory respecting the pbcs

plumed benchmark can now read trajectory files

---

configure
configure.ac
new-manual/gpu.md

@GiovanniBussi @gtribello 
I have updated the `gpu.md` file in the new manual with the information on the currently working openacc actions.
I also added some installation instructions, I would keep them there until we have something stabler.
On top of that I modified configure.ac in order to remove it from the scope of #1268 and, mainly, to make easier to setup openacc.

New manual/gpu

---

src/cltools/Driver.cpp
src/cltools/GenExample.cpp
src/core/ActionShortcut.cpp
src/core/ActionShortcut.h

As title, I think this should save some time in the manual, tests and support sites by avoiding copying the vector of strings that are produced by the shortcuts.
If you want a copy you still can call `vector<string> cnames = as->getSavedOutputs();` instead of `const auto & cnames = as->getSavedOutputs();`.

 Passing by reference the string vectors of actionShortcuts
