- src/bias/MetaD.cpp
- src/bias/PBMetaD.cpp
Make sure these boxes are checked before submitting your pull request:
> Marco De La Pierre: added WALKERS_DIR option for WALKERS_MPI

- src/bias/MaxEnt.cpp
- user-doc/bibliography.bib
Make sure these boxes are checked before submitting your pull request:
> Updates and Fixes to MaxEnt documentation

- src/pamm/HBPammHydrogens.cpp
- src/pamm/HBPammMatrix.cpp
- src/pamm/HBPammObject.cpp
- src/pamm/HBPammObject.h
- src/pamm/PAMM.cpp
- src/pamm/PammObject.cpp
- src/pamm/PammObject.h
- src/tools/ForwardDecl.cpp
This pull request contains changes in headers automatically generated by plumedbot on Travis-ci.
Please review them and, if correct, merge them to branch master.
> Plumedbot pull request

- src/analysis/Analysis.cpp
- src/analysis/Analysis.h
- src/analysis/AnalysisWithLandmarks.cpp
- src/analysis/AnalysisWithLandmarks.h
- src/analysis/ClassicalMultiDimensionalScaling.cpp
- src/analysis/Histogram.cpp
- src/analysis/LandmarkRegister.cpp
- src/analysis/LandmarkRegister.h
- src/analysis/LandmarkSelectionBase.cpp
- src/analysis/PCA.cpp
Hi @gtribello 
I am slowly replacing delete statements with std::unique_ptr. In this commit I did it for the `analysis` module, which however I don't feel I understand well enough. Could you have a look and tell me if this can be merged?
Thanks!
Giovanni
PS Tests on travis should be ok (though osx is frozen now), but I will anyway wait for all the tests to complete.
> unique_ptr: analysis

- src/bias/PBMetaD.cpp
@carlocamilloni @maxbonomi 
I replaced pointers with unique_ptr's in PBMetaD. Could you please check if what I did is ok? In case so I will merge it to master. Thanks!
Giovanni
> unique_ptr: PBMETAD

- src/drr/DynamicReferenceRestraining.cpp
- src/drr/drrtool.cpp
- user-doc/EABFMOD.md
Fix #296.
Add a header page
Travis-CI is running.
> Move eABF/DRR documentations to additional modules

- src/ves/MD_LinearExpansionPES.cpp
- user-doc/VES.md
Some minor changes to VES module, mainly manual and some cppcheck style fixes. 
> Minor changes to VES module

- src/ves/MD_LinearExpansionPES.cpp
> Fix for issue #306 with VES

- CHANGES/v2.4.md
- patches/qespresso-6.2.config
- patches/qespresso-6.2.diff/PW/src/forces.f90
- patches/qespresso-6.2.diff/PW/src/forces.f90.preplumed
- patches/qespresso-6.2.diff/PW/src/plugin_ext_forces.f90
- patches/qespresso-6.2.diff/PW/src/plugin_ext_forces.f90.preplumed
- patches/qespresso-6.2.diff/PW/src/plugin_initialization.f90
- patches/qespresso-6.2.diff/PW/src/plugin_initialization.f90.preplumed
- patches/qespresso-6.2.diff/PW/src/run_pwscf.f90
- patches/qespresso-6.2.diff/PW/src/run_pwscf.f90.preplumed
Replace #311
@ralf-meyer Could you please check if this is ok? Thanks
Giovanni
> Added patch for QE 6.2

- src/colvar/PathMSDBase.cpp
- src/tools/RMSD.cpp
Hi,
regarding discussion in issue #272, I changed original Intel-compiler dependent vectorization pragmas to more universal OpenMP v4.0 pragmas.
We discussed the code could appear in release v2.4.
The test for the close structure remains, this is just a compiler thing, not affecting the numbers, just performance.
Yes, see https://travis-ci.org/jpazurikova/plumed2/builds/296291565
In case of any problems, please let me know.
Regards,
Jana Pazúriková
> Change intel pragmas to OpenMP v4+ pragmas

- src/ves/BF_Cosine.cpp
- src/ves/BF_Fourier.cpp
- src/ves/BF_Sine.cpp
> Minor changes to VES manual

- src/adjmat/ContactMatrix.cpp
@gtribello can you double check this fix before I merge? Thanks
> Fixed warning

- user-doc/tutorials/others/ves-lugano2017-01-metad.txt
- user-doc/tutorials/others/ves-lugano2017-02-ves1.txt
- user-doc/tutorials/others/ves-lugano2017-04-kinetics.txt
- user-doc/tutorials/others/ves-lugano2017-metad/Example2/ReweightDistance/plot.gpi
- user-doc/tutorials/others/ves-lugano2017-ves1/Example1/Barrier_calculation/run.sh
- user-doc/tutorials/others/ves-lugano2017-ves1/Example2/plotTargetDistrib.gpi
Some minor fixes to the VES tutorial. No functionality changes.
I would like my code to appear in release __2.4__
> V2.4 tutorial fixes

- src/vesselbase/ActionWithVessel.cpp
I think this fixes #417.
Regtests are passing now.
> Test fix #417

- src/ves/PEOPLE-VES
Updated PEOPLE-VES to include the contribution from @invemichele. 
> updated PEOPLE-VES

- src/piv/PIV.cpp
@SilvioPipolo I want to merge these fixes in printf formats. Let me know if there is any problem with this. Thanks
I would like my code to appear in release __v2.5__
> Fixed LGTM errors

- user-doc/tutorials/others/isdb-2/TUTORIAL_SAXS-AACG/martiniFormFactor_p2.py
- user-doc/tutorials/others/isdb-2/TUTORIAL_SAXS-AACG/martiniFormFactor_p3.py
fixed python files for isdb SAXS tutorial 
I would like my code to appear in release v2.5
- [X ] changes to a module not authored by you
- [ X] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.
> Fixed files martiniFormFactor

- src/multicolvar/CoordinationNumbers.cpp
A bug fix on multicolvar::CoordinationNumbers::compute(). The derivatives were missing two terms. The version 2.4 seems to be the oldest version this bug appears.
I would like my code to appear in release v2.4 and later
> fixed derivatives in CoordinationNumbers

- src/ves/PEOPLE-VES
Updated PEOPLE-VES with the contributions of @PabloPiaggi 
> Update of PEOPLE-VES

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
Added note that contributed modules should be open source.
> modules should be open source

- src/tools/Random.cpp
Fixes #493. I open a pull request to run all tests. If there are no failures I will merge it to 2.5 as a bug fix.
> Fixes #493

- user-doc/VES.md
Fix links to old lugano tutorials due to changes in 5770d9120c4baa908a8d362b1695ba13b9879cce
Same change as done previously for master branch. Cherry-picked commit from master branch. 
I would like my code to appear in release v2.5
> Update VES.md to fix links to tutorial

- src/isdb/MetainferenceBase.cpp
change iseed definition in MetainferenceBase
- [ X] changes to a module not authored by you
- [X ] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.
> change iseed definition

- src/maze/Random_MT.cpp
- src/maze/Random_MT.h
@jakryd could you please check this pull request and approve it?
See #549 for more explanation
I would like my code to appear in release __v2.6__
> Fix maze to avoid unique global symbols

- patches/namd-2.14.config
- patches/namd-2.14.diff
Patch for new NAMD 2.14 released on 05.08.2020
I would like my code to appear in next release
> Add patch for NAMD 2.14

- src/bias/MetaD.cpp
This fixes the issues reported in the mailing list https://groups.google.com/g/plumed-users/c/maD46ZOfss4/m/gXtqFcwoCAAJ
I would like my code to appear in release v2.5 and above
> fixed exponential overflow of rct in case of non-tempered metad

- patches/gromacs-2020.4.diff/src/gromacs/mdlib/expanded.cpp
- patches/gromacs-2020.4.diff/src/gromacs/mdlib/expanded.cpp.preplumed
- patches/gromacs-2020.4.diff/src/gromacs/mdlib/expanded.h
- patches/gromacs-2020.4.diff/src/gromacs/mdlib/expanded.h.preplumed
- patches/gromacs-2020.4.diff/src/gromacs/mdrun/md.cpp
- src/tools/IFile.h
@carlocamilloni this is the branch I am planning to merge.
It includes #603 (ported to gmx 2020.4) and #621
Thanks! Giovanni
> Lambda metadynamics gmx 2020.4

- src/opes/OPESmetad.cpp
This is to change an external link in the doc of OPES_METAD, so that it points to a separate repository.
After this PR is merged, I will be able to safely remove the postprocessing folder from #622 and also that PR can be merged.
I would like my code to appear in release v2.7
> updating link to postprocessing scripts

- .travis.yml
- src/adjmat/DumpGraph.cpp
- src/bias/MetaD.cpp
- src/bias/PBMetaD.cpp
- src/colvar/PathMSDBase.cpp
- src/core/ActionAtomistic.cpp
- src/core/ActionWithArguments.cpp
- src/core/Atoms.cpp
- src/crystallization/GradientVessel.cpp
- src/isdb/SAXS.cpp
- src/piv/PIV.cpp
- src/tools/ERMSD.h
- src/tools/MultiValue.cpp
- src/tools/MultiValue.h
- src/ves/MD_LinearExpansionPES.cpp
- src/vesselbase/StoreDataVessel.h
- use size_t over unsigned int 
- avoids integer overflow on multiplication
No preference
> Fixing LGTM size_t

- src/colvar/Energy.cpp
Added warning about missing long tail corrections in the ENERGY colvar, see #567 
I would like my code to appear in release v2.5 and above (but probably could be added also to older versions...)
> ENERGY doc: warning about tail corrections

- src/opes/OPESmetad.cpp
- Zed
- Mergeable
@invemichele
> OPES: added some more OPENMP parallelism

- src/opes/OPESexpanded.cpp
This PR adds OpenMP parallelization to OPES_EXPANDED. Needs to be reviewed and approved by @invemichele.
Here's a benchmark of the chignolin mini protein using 1 GPU and different number of OpenMP threads:
| Threads |Performance (ns//day) |
| ---- | --------------- |
|  1   |  172.547     |
|  2   |   234.880    |
|  3   |     271.956  |   
|  4   |    277.515   |
|  6   |    300.478   |
|  8   |    310.016   |
~4000 DeltaFs were used for this benchmark.
I would like my code to appear in any release
I think that the current regtests should cover this changes but I am happy to add one if needed.
> Add OpenMP to OPES_EXPANDED

- user-doc/AdditionalModules.md
- user-doc/Installation.md
I have always found that the [page about modules configuration](https://www.plumed.org/doc-master/user-doc/html/mymodules.html) is quite hidden in the documentation.
This PR adds a reference to modules in the main installation page, under [configuring PLUMED](https://www.plumed.org/doc-master/user-doc/html/_installation.html#ConfiguringPlumed), and also in the [additional modules](https://www.plumed.org/doc-master/user-doc/html/_add_mod.html) page.
The goal is to make it easier to find the instructions on how to enable modules, by putting a reference to it where it might be intuitive to look for it. There might be better ways to achieve this goal, this PR is my attempt.
I would like my code to appear in release __v2.5 and above__
> [doc] adding reference to modules configuration

- src/sasa/sasa_HASEL.cpp
- src/sasa/sasa_LCPO.cpp
I updated the documentation of the sasa module (to fix some formatting issues)
I would like my code to appear in release 2.8
- [ X ] new module contribution or edit of a module authored by you
- [ X  ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 
- [ X  ] I added a new regtest or modified an existing regtest to validate my changes.
- [  X ] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).
> Modified the description of the sasa module

- src/ves/BasisFunctions.cpp
- src/ves/CoeffsBase.cpp
- src/ves/CoeffsBase.h
- src/ves/CoeffsMatrix.cpp
- src/ves/CoeffsVector.cpp
- src/ves/CoeffsVector.h
- src/ves/LinearBasisSetExpansion.cpp
- src/ves/LinearBasisSetExpansion.h
- src/ves/MD_LinearExpansionPES.cpp
- src/ves/Opt_BachAveragedSGD.cpp
- src/ves/Optimizer.cpp
- src/ves/Optimizer.h
- src/ves/OutputBasisFunctions.cpp
- src/ves/OutputTargetDistribution.cpp
- src/ves/TD_Grid.cpp
- src/ves/TargetDistribution.cpp
- src/ves/TargetDistribution.h
- src/ves/VesBias.cpp
- src/ves/VesBias.h
- src/ves/VesLinearExpansion.cpp
@valsson I spent some time in trying to remove all `delete` statements in the ves module. This should be a step forward towards exception safety, and should make the code more readable showing clearly which pointers are owning (unique_ptr) and which ones are aliases (raw pointers).
I hope I didn't make mistakes. Regtests should be fine. Please let me know what you think and if I can merge.
> Using unique_ptr in ves module

- src/sasa/sasa_LCPO.cpp
I tried to solve the issue with cppcheck 2.6.1. Thanks for pointing this out.
I would like my code to appear in release 2.8
- [X ] new module contribution or edit of a module authored by you
- [X ] the module I added or modified contains a `COPYRIGHT` file with the correct license information. Code should be released under an open source license. I also used the command `cd src && ./header.sh mymodulename` in order to make sure the headers of the module are correct. 
- [ X] I added a new regtest or modified an existing regtest to validate my changes.
- [X ] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).
> try and solve cppcheck 2.6.1 warnings

- python/Makefile
Self explained 
I would like my code to appear in release v2.5 and higher
> Fix typo that I noticed

- src/bias/MetaD.cpp
- src/opes/OPESexpanded.cpp
- src/opes/OPESmetad.cpp
Several small changes to the OPES documentation.
Also a better description of the CALC_WORK keyword in METAD (same as OPES_METAD).
> some doc improvements

- src/adjmat/Sprint.cpp
- user-doc/bibliography.bib
I added a reference for SPRINT and fixed a tiny typo in its doc.
I would like my code to appear in release v2.7 and later
> Improve SPRINT doc

- src/opes/OPESmetad.cpp
- user-doc/bibliography.bib
- user-doc/tutorials/others/opes-metad.txt
small changes to the documentation
I would like my code to appear in release __2.8__
> added reference to OPES explore paper

- src/opes/ECVmultiThermal.cpp
- src/opes/ECVmultiThermalBaric.cpp
- src/opes/OPESexpanded.cpp
- src/opes/OPESmetad.cpp
- user-doc/OPES.md
- user-doc/bibliography.bib
Fixing a confusing wrong sign in two formulas of the OPES doc, and other minor mistakes and typos in the doc.
> fixes to OPES doc v2.8

- user-doc/tutorials/aa-masterclass-22-03.txt
Sorry, I read it again and made various improvements to the readability of the tutorial
I would like my code to appear in release __master__
> masterclass 22.3 improved readability

- user-doc/tutorials/aa-masterclass-22-03.txt
> fix wrong reference

- user-doc/tutorials/aa-masterclass-22-05.txt
Masterclass documentation for tomorrow.
I would like my code to appear in release **master**
> Masterclass 22.05

- user-doc/tutorials/a-masterclass-22-06.txt
Hi,
A minor edit of PR #819 with the (hopefully) correct termination character on the masterclass file. 
CC @hockyg
> [Ready to Merge] EDS Masterclass PR 2

- user-doc/tutorials/a-masterclass-22-11.txt
Tutorial for Masterclass 22-11
I would like my code to appear in release master
Not relevant
> Masterclass 22-11

- user-doc/tutorials/a-masterclass-22-11.txt
Masterclass-22-11: Missing keyword in Exercise 4
I would like my code to appear in release master
> Masterclass-22-11: Missing keyword in Exercise 4

- user-doc/tutorials/a-masterclass-22-11.txt
masterclass-22-11: fix header
I would like my code to appear in release master
> masterclass-22-11: fix header

- src/ves/BF_CubicBsplines.cpp
- src/ves/BF_Gaussians.cpp
- src/ves/BF_Wavelets.cpp
- user-doc/bibliography.bib
Update citations for wavelet basis functions in VES module.
I would like my code to appear in release v2.8 and master
> Update citations for wavelet basis functions in VES module.

- user-doc/tutorials/a-masterclass-22-12.txt
These are the instructions for Masterclass 22.12
I would like my code to appear in the **master** branch
> Masterclass 22.12 docs

- user-doc/tutorials/a-masterclass-22-12.txt
Correct visualization issue with masterclass 22.12 docs. I am assuming that the issue is in the examples as discussed in #845 .
I would like my code to appear in the **master** branch
> Masterclass 22.12 docs - correct visualization

- src/isdb/Metainference.cpp
- src/isdb/MetainferenceBase.cpp
This PR fixes #847.
I'm not happy with the `if`s inside the loops, and fixing this would be easy for the `SP` versions, but for `SPE` there might be zeros for just some of the replicas, so I'm not sure what would be a good approach in this case.
Let me know if you have any better ideas.
I would like my code to appear in release 2.7
> Fixed division by zero when SIGMA_MEAN0=0 in Metainference

- src/opes/OPESexpanded.cpp
- src/opes/OPESmetad.cpp
I added one missing `unsigned long`
pushing to the fix-852 branch, hope is the correct thing to do
I would like my code to appear in release __2.9__
> small adjustments for long long in opes

- src/ves/MD_LinearExpansionPES.cpp
Since we are here...
This PR changes the step in  [VES PES MD](https://www.plumed.org/doc-v2.7/user-doc/html/ves_md_linearexpansion.html) from `unsigned` to `long long unsigned`, to allow for longer simulations.
@valsson we had to do this change to perform some of the simulations in this paper https://arxiv.org/abs/2208.04942, but then we never pushed it to the official repo. (cc @dhimanray, @valeriorizzi, @narjesansari)
A similar change could be done also in `src/cltools/pesmd.cpp` that now uses an `int` to count steps.
I would like my code to appear in release __2.9__
> `long long unsigned` for step in VES MD

- src/isdb/Metainference.cpp
- src/isdb/MetainferenceBase.cpp
This PR backports a fix that has been merged to `master` and that, IMHO, should be in 2.7 and 2.8 (see #847 for details).
I'll not create another PR for 2.8, but feel free to ask me to do so if you think that makes things easier for you :)
I would like my code to appear in release 2.7 and 2.8
> Backports fix to metainference when sm2 = 0

- src/opes/ECVumbrellasLine.cpp
- user-doc/OPES.md
- user-doc/tutorials/a-masterclass-22-03.txt
- user-doc/tutorials/others/opes-masterclass.txt
- user-doc/tutorials/others/opes-metad/FES_from_Reweighting.py
- user-doc/tutorials/others/opes-metad/FES_from_State.py
Various small adjustments to the OPES masterclass and tutorials
I would like my code to appear in release __2.9__
> small improvements for OPES tutorials

- user-doc/tutorials/a-masterclass-22-13.txt
Tutorial Masterclass-22-13
I have added a tutorial for the Masterclass 22-13. Thank you very much.
> Tutorial Masterclass-22-13

- user-doc/tutorials/a-masterclass-22-13.txt
I have added a link to a folder with the results. Thank you very much!
> update Masterclass 22-13 with results

- user-doc/tutorials/a-masterclass-22-15.txt
Masterclass tutorial
- [x ] new module contribution or edit of a module authored by you
- [ x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.
> theory and background for FISST masterclass

- src/bias/MetaD.cpp
> fix(metad_warning): fix metad warning for grid larger than 1/2 sigma when using ADAPTIVE and GRID

- src/isdb/SAXS.cpp
We added a ONEBEAD representation for SANS routine, integrated with previously introduced SASA calculation code by Andrea Arsiccio. This feature allows to take into account the hydration layer contribution in SANS intensity calculation.
I would like my code to appear in release 2.9
> SANS support added with ONEBEAD representation

- src/piv/PIV.cpp
This is meant to solve the non-thread-safety of PIV variables (see [this comment](https://github.com/plumed/plumed2/pull/370#issuecomment-419094411)). Specifically:
- Before this fix, a number of objects are allocated as `static` and shared between all instances of the PIV object.
- After this fix, these objects are only shared between instances of the PIV object created within the same PlumedMain object
As a result, it should be possible to allocate multiple PlumedMain objects without interference (e.g., for multithreading).
To minimize code changes, I defined a [struct](https://github.com/plumed/plumed2/blob/d927afee7f3427c1559939e55e437d71d5ba26a1/src/piv/PIV.cpp#L213-L220) containing all the required data structures. The first PIV instance [allocates an owning …
> Made PIV implementation thread safe

- src/funnel/FPS.cpp
- src/maze/Memetic.cpp
- src/maze/Memetic.h
- src/maze/Optimizer.cpp
- src/maze/Optimizer.h
- src/maze/Random_Acceleration_MD.cpp
- src/maze/Random_Walk.cpp
- src/maze/Simulated_Annealing.cpp
- src/maze/Steered_MD.cpp
- src/piv/PIV.cpp
I removed a number of not required explicit destructors. This was done basically:
- using objects instead of pointers where possible and easy to do without too many changes
- using unique_ptr instead of raw pointers in other cases
Please let me know if there is any objections, or I will merge this in a couple of weeks.
maze module: @jakryd 
funnel module: @h2nch2co2h 
piv module: @SilvioPipolo
I would like my code to appear in release __v2.9__
> Remove unnecessary destructors

- .github/workflows/ci.yml
- configure
- configure.ac
- src/pytorch/PytorchModel.cpp
- user-doc/PYTORCH.md
Small bug fixes and updates related to the Pytorch module documentation.
- I noticed that there was a bug in the documentation of the pytorch module. Due to recent changes in section headers, only the first two sections were shown.
- I also updated some instructions on how to verify that the configuration with libtorch is succesful. 
- I updated the module doc and the CI instructions with the link to the latest libtorch version (1.13.1). Before the Long Term Support version (1.8.2) was recommended and used in the CI, but it has been [discontinued](https://pytorch.org/blog/pytorch-enterprise-support-update/).
- I updated the behavior of the PLUMED_CHECK_CXX_PACKAGE function in configure  when linking against multiple libraries. Now the check is done against all the libraries at once, …
> Pytorch documentation fix and update

- src/crystallization/EnvironmentSimilarity.cpp
The Environment Finder application is a tool to determine the environments needed for the EnvironmentSimilarity collective variable. The link to the Environment Finder app in the manual was obsolete. I updated the link to a (hopefully) more stable one.
I would like my code to appear in release v2.7, v2.8, v2.9, and master. Should I open independent pull requests?
This is a change to code authored by me, inside a module authored by @gtribello
> Update link to Environment Finder - Target v2.7

- CHANGES/v2.8.md
- src/opes/OPESexpanded.cpp
- user-doc/tutorials/others/opes-metad/FES_from_Reweighting.py
- user-doc/tutorials/others/opes-metad/FES_from_State.py
- user-doc/tutorials/others/opes-metad/State_from_Kernels.py
- OPES_EXPANDED is now numerically robust to avoid possible overflows with large systems. Thanks to @valeriorizzi for spotting the issue
- minor cleanup of python scripts in the OPES tutorial
Without this fix when running e.g. multithermal simulations with a large system, one could get `-inf` as DeltaF value for the temperatures farthest away. This will no longer happen.
I would like my code to appear in release __v2.8__ and newer
> make OPES_EXPANDED robust to overflow

- json/Makefile
This change adds a test on syntax.json after it is created to ensure that it is all written in valid json.
I think it is useful to include this as soon as possible as if there are problems in the syntax.json file it causes problems with the nest and the tutorials building.  I would put it in v2.9 as v2.9 is tested on the nest and on the tutorials pages.
> Json check

- patches/qespresso-6.2.diff/PW/src/plugin_ext_forces.f90
- patches/qespresso-7.0.diff/PW/src/plugin_ext_forces.f90
The modifications from #962 but rebased on the v2.9, the modification passes the [tests](https://github.com/plumed/test-plumed-qe/actions/runs/5736904285) with qe7.0
I would like my code to appear in release 2.9
> Plumed now fetches the masses from pw.x correctly (v2.9)

- CHANGES/v2.9.md
Updated the Changelog with the modification of #970
> Update v2.9.md with the qe changes

- src/opes/OPESmetad.cpp
- user-doc/bibliography.bib
add journal reference
I would like my code to appear in release __v2.8__ and newer
> update OPES explore bibliography

- src/core/DomainDecomposition.cpp
@GiovanniBussi I think this change should give your speed up on the input you discussed in #1025.  This also ensures that the code still works when you run with DomainDecomposition, however.
- [ x] changes to code or doc authored by PLUMED developers, or additions of code in the core or within the default modules
- [ x] I agree to transfer the copyright of the code I have written to the PLUMED developers or to the author of the code I am modifying.
- [ x] I verified that all regtests are passed successfully on [GitHub Actions](https://github.com/plumed/plumed2/actions).
> Removed second build of active atom list to address issue #1025

- configure
- configure.ac
As title
I would like my code to appear in release v2.10? If you ask, I can back port this to v2.8, it is just a single commit with 8 inverted letters that I can be rebased easily
> Corrected a typo in fussy warning:-Wredundant-delcs -> -Wredundant-decls

- json/Makefile
- src/analysis/SelectWithStride.cpp
- src/cltools/Driver.cpp
- src/cltools/GenJson.cpp
- src/cltools/kT.cpp
- src/crystallization/Q3.cpp
- src/crystallization/Q4.cpp
- src/crystallization/Q6.cpp
- src/function/Custom.cpp
- src/isdb/Jcoupling.cpp
- src/isdb/Select.cpp
- src/manyrestraints/LWalls.cpp
- src/manyrestraints/UWalls.cpp
- src/maze/Optimizer_Bias.cpp
- src/multicolvar/FilterBetween.cpp
- src/multicolvar/FilterLessThan.cpp
- src/multicolvar/FilterMoreThan.cpp
In the nest and tutorials the first line of the documentation for actions appears in the tooltip that appears when you hover over the action name.  This line of text should thus provide a brief summary of what the action does.  To make this renderable this description should not include anything that needs to be rendered by Doxygen (i.e. equations and ref commands).  I found some places in PLUMED where people have included equations and ref commands in that first line of doxygen input.
This commit adds a check when the json syntax file is rendered to ensure folks do not have backslash characters in that first line of syntax. I think this should capture all the doxygen commands that people might use in these lines.
It also removes the few places where people have included equations and so …
> Removed Doxygen characters from first line of documentation

- regtest/.gitignore
- src/.gitignore
The sizeshape directories were ignored and this generates some warning messages while doing manteinance
I would like my code to appear in release v2.10
> Update (src|regtest)/.gitignore - missing sizeshape

- developer-doc/.gitignore
I simply updated the gitignore in developer-doc to ignore all unnecessary files from `make -C developer-doc coverage` output
I would like my code to appear in release __v2.9__
> Now git ignores coverage output

- python/plumed.pyx
I am working on some (small) modifications on the python package, while running the tests I found that the python module uses `delim_whitespace` that is deprecated from `pandas2.20`, (see [the manual](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html))
I used the suggested ` sep="\s+" ` option, which should be backward-compatible also with older pandas versions
I would like my code to appear in release 2.11 (or before?)
> fixed deprecation warning from pandas

- Makefile
- src/Makefile
- src/maketools/codecheck
- src/maketools/plumedcheck
This merges and solves the conflicts that #1192 creates in v2.10
I would like my code to appear in release __v2.10__
> Safemerge/cppcheck v2.9 into v2.10

- src/colvar/MultiColvarTemplate.h
- src/core/ParallelTaskManager.h
- src/secondarystructure/SecondaryStructureBase.h
- src/volumes/ActionVolume.h
@gtribello I wanted to show this small change, it its fast to implement and not much invasive, and might help in maintain the new stuff. It will need to be adapted to the new  changes
This makes the classes that use the parallel task manager (and the task manager itself) a little less verbose and more "self documented".
It also remove the risk of writing the wrong parallel task manager in the keyword declaration
> NIT:self-documenting typing for paralletaskmanager

- src/colvar/MultiColvarTemplate.h
- src/core/ParallelTaskManager.h
- src/secondarystructure/SecondaryStructureBase.h
- src/volumes/ActionVolume.h
> Revert "NIT:self-documenting typing for paralletaskmanager"

- src/colvar/ColvarInput.cpp
- src/colvar/ColvarInput.h
- src/colvar/MultiColvarTemplate.h
- src/core/ParallelTaskManager.h
- src/tools/Pbc.cpp
@gtribello I removed the comments that triggered @github-advanced-security  with the commented out code that I introduced with #1206 
I did not removed the "commented code" I used as examples in the documentation for OpenACC.h
> removing the "commented out code"

- src/colvar/MultiColvarTemplate.h
- src/core/ParallelTaskManager.h
- src/secondarystructure/SecondaryStructureBase.h
- src/volumes/ActionVolume.h
This should fix the template problem of #1215, I would wait for it to fail the CI in the same way as final-backpropegation before merging this
> NIT:self-documenting typing for paralletaskmanager (allegedly fixed)

- .ci/push
- new-manual/build_manual.py
- new-manual/mkdocs.yml
- new-manual/parsing.md
- new-manual/vim.md
- src/cltools/GenJson.cpp
This PR does the following:
1. It ensures that the site directory that is generated by mkdocs is pushed to user-doc/html.  This should ensure that the link on plumed.org can find the new manual.
2. It adds links to the developer docs in the new manual
3. It fixes the links in the syntax.json file so that if you click on an action in example inputs they should link to the corresponding action pages in the new documentation
I would like my code to appear in release 2.11
> Fixed link for new user manual

- new-manual/build_manual.py
- src/cltools/Driver.cpp
- src/cltools/GenJson.cpp
- src/maketools/makeModuleMap
This PR adds functionality that ensures that new manual pages are created for the command-line tools.  To achieve this aim I added code to gen_json to output information on the command line tools to the syntax.json file.  I also had to modify makeModuleMap so that it detects PLUMED_REGISTER_CLTOOL as well as PLUMED_REGISTER_ACTION.  @Iximiel can you double check that I did that OK, please.
I would like my code to appear in release 2.11
> Cltool docs

- src/crystdistrib/.gitignore
- src/crystdistrib/BopsShortcut.cpp
- src/crystdistrib/DopsShortcut.cpp
- src/crystdistrib/Quaternion.cpp
- src/crystdistrib/QuaternionBondProductMatrix.cpp
- src/crystdistrib/QuaternionProductMatrix.cpp
- src/crystdistrib/RopsShortcut.cpp
- src/crystdistrib/module.md
- src/crystdistrib/module.yml
This commit adds documentation to the crystdistrib module.  This documentation was written by Jake McKibbin.
I would like my code to appear in release 2.11
> Added documentation for crystdistrib module

- new-manual/build_manual.py
I realised that I made a mistake with the way that I am calling PlumedToHTML in the new documentation builder.  The negative side effect of this is that the modals that are there so you can look at the auxiliary input files that plumed uses.  (these are things like the file that is passed to REFERENCE for RMSD) do not actually appear.  This small change resolves this problem.  With this change you can use the modals to look at the auxiliary inputs.
I would like my code to appear in release 2.11
> Fix to new documentation builder for modals for input files 

- src/ves/LinearBasisSetExpansion.cpp
- src/ves/LinearBasisSetExpansion.h
As discussed in PR #1231 @valsson wants the variable that I introduced, `gfmt_` to be renamed `grid_fmt_`.  This PR makes this small change.
> Fix ves grid fmt name for omar

- patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedMDModule.cpp
- patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedOptions.h
- patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedforceprovider.cpp
- patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedforceprovider.h
- patches/gromacs-2025.0.diff/src/gromacs/applied_forces/plumed/plumedforceprovider.h.preplumed
- patches/gromacs-2025.0.diff/src/gromacs/mdrun/runner.cpp
- patches/gromacs-2025.0.diff/src/gromacs/mdrun/runner.cpp.preplumed
- patches/gromacs-2025.0.diff/src/gromacs/mdrunutility/mdmodulesnotifiers.h
- patches/gromacs-2025.0.diff/src/gromacs/mdrunutility/mdmodulesnotifiers.h.preplumed
I am adding the replex check following the discussion in #1162
I would like my code to appear in release __V2.10__
> Checking for replex in the gromacs 2025 patch

- python/plumed.pyx
Added an argument that is not callable to cython.nogil to fix a compilation error I had:
```
plumed_force_cython=yes
importing cython
Compiling plumed.pyx because it changed.
[1/1] Cythonizing plumed.pyx
Error compiling Cython file:
------------------------------------------------------------
...
safe.flags=flags
cplumed.plumed_error_init(&error)
nothrow.ptr=&error
nothrow.handler=cplumed.plumed_error_set
with cython.nogil():
^
------------------------------------------------------------
plumed.pyx:190:20: The nogil directive takes one compile-time boolean argument
Traceback (most recent call last):
File "setup.py", line 133, in <module>
ext_modules=cythonize(ext_modules,language_level=3)
File "/lmb/home/jkrieger/anaconda3/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line …
```
> add cython nogil arg None

- src/colvar/MultiColvarTemplate.h
- src/core/ParallelTaskManager.h
- src/secondarystructure/SecondaryStructureBase.h
- src/volumes/ActionVolume.h
@gtribello with "out of the box" [here](https://github.com/plumed/plumed2/pull/1243#issuecomment-2821312699) I was referring with these modifications.
> redo-applyforces compiles with openacc

- src/colvar/MultiColvarTemplate.h
- src/core/ParallelTaskManager.h
- src/secondarystructure/SecondaryStructureBase.h
- src/volumes/ActionVolume.h
> Revert "Added new mechanism for forces in ParallelTaskManager"

- src/cltools/Benchmark.cpp
This is a followup to #1252: the idea is to load a trajectory file and to replicate it. This should bring relatively more realistic benchmarks.
In the way I implemented the replicas it is possible to multiply also the "synthetic" atom distributions to get even different configurations.
I am not very fond of the new options names for the CLI ("--repeat*", *=XYZ) but I can't came with better names on my own :cry: 
I would like my code to appear in release v2.11
> Benchmark trajectory multiplication

- src/liquid_crystal/.gitignore
@carlocamilloni
The liquid_crystal module lacks the .gitignore file, if @humeniuka is ok I am copy-pasting the default one in their module.
> Using the default .gitignore in liquid_crystal

- src/tools/SwitchingFunction.cpp
I just found this nasty bug of mine into the accelerable switching function, now when calling "calculate" the switch will return the correct values,
> Bugfix in switching function

- CHANGES/v2.10.md
Some links in the changelog where still pointing to the plumed school, I corrected the to point to the tutorial site instead
I would like my code to appear in release __v2.10__
> Corrected broken links in the v2.10 changelog
